spring:
   profiles:
     active:
     - dev  #
---
spring:
  profiles: dev  #kaifa
  application:
       name: microservice-microservicecloud-config-llb-dev
---
spring:
  profiles: test  #test
  application:
       name: microservice-microservicecloud-config-llb-test
#utf-8