spring:
   profiles:
     active:
     - dev
---


server:
  port: 8001
spring:
     profiles: dev
     application:
      name: microservicecloud-dept-client   
     datasource:
      type: com.alibaba.druid.pool.DruidDataSource          
      driver-class-name: com.mysql.cj.jdbc.Driver             
      url: jdbc:mysql://localhost:3306/C1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8            
      username: root
      password: 123456
      dbcp2:
       min-idle: 5                                         
       initial-size: 5                                      
       max-total: 5                                       
       max-wait-millis: 200      
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      
  type-aliases-package: com.llb.springcloud.bean   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml    
  
  
 
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/  
     
  instance:
     instance-id: provider-dept8001
                                    
     prefer-ip-address: true

info:
  app.name: llb-microservicecloud
  company.name: www.llb.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$  
                   
---   
server:
  port: 8002
spring:
   profiles: test
   application:
    name: microservicecloud-dept   
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: com.mysql.cj.jdbc.Driver             
    url: jdbc:mysql://localhost:3306/C2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8              
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                     
      max-total: 5                                         
      max-wait-millis: 200                               
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      
  type-aliases-package: com.llb.springcloud.bean   
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml    
  
 
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/  
     
  instance:
     instance-id: provider-dept8002
                                    
     prefer-ip-address: true

info:
  app.name: llb-microservicecloud
  company.name: www.llb.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
     
