eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-dept   

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka/